# Generated by Django 4.2.16 on 2026-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('component_type', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20)),
                ('source_of_blood', models.CharField(choices=[('donation', 'Donation'), ('receiver_recovery', 'Receiver Recovery Return'), ('camp', 'Camp')], default='donation', max_length=30)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['blood_group', 'component_type', 'source_of_blood', 'source_name'],
                'unique_together': {('blood_group', 'component_type', 'source_of_blood', 'source_name')},
            },
        ),
    ]
