# Generated by Django 5.2.11 on 2026-03-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_donor_blood_group_alter_donor_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
