# Generated by Django 4.2.16 on 2026-03-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='role_type',
        ),
    ]
