# Generated by Django 4.2.16 on 2026-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_donor_health_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('active', 'Active & Available'), ('unavailable', 'Temporarily Unavailable'), ('medical', 'Medical Hold'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='status_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
