# Generated by Django 5.2.11 on 2026-03-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('users', '0005_alter_donor_blood_group_alter_donor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Camp', 'Camp')], max_length=20)),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
                ('temperature_c', models.FloatField()),
                ('pulse_rate', models.IntegerField()),
                ('hemoglobin', models.FloatField(blank=True, null=True)),
                ('is_on_medication', models.BooleanField(default=False)),
                ('medication_details', models.TextField(blank=True, null=True)),
                ('had_recent_fever', models.BooleanField(default=False)),
                ('fever_details', models.TextField(blank=True, null=True)),
                ('donated_last_3_months', models.BooleanField(default=False)),
                ('recent_donation_details', models.TextField(blank=True, null=True)),
                ('has_chronic_illness', models.BooleanField(default=False)),
                ('chronic_illness_details', models.TextField(blank=True, null=True)),
                ('used_steroids', models.BooleanField(blank=True, null=True)),
                ('steroid_details', models.TextField(blank=True, null=True)),
                ('had_major_surgery', models.BooleanField(blank=True, null=True)),
                ('surgery_details', models.TextField(blank=True, null=True)),
                ('is_pregnant', models.BooleanField(blank=True, null=True)),
                ('is_breastfeeding', models.BooleanField(blank=True, null=True)),
                ('has_heavy_menstruation', models.BooleanField(blank=True, null=True)),
                ('recent_delivery_or_miscarriage', models.BooleanField(blank=True, null=True)),
                ('female_additional_details', models.TextField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='users.donor')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(choices=[('Diabetes', 'Diabetes'), ('Heart Disease', 'Heart Disease'), ('Cancer', 'Cancer'), ('Tuberculosis', 'Tuberculosis'), ('Hepatitis', 'Hepatitis'), ('HIV', 'HIV'), ('None', 'None')], max_length=50)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='donations.donorsurvey')),
            ],
        ),
    ]
