# Generated by Django 4.2.16 on 2026-03-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationrecord_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned to Inventory')], default='scheduled', max_length=20),
        ),
    ]
