# Generated by Django 5.2.11 on 2026-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_donorresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='component_type',
            field=models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20),
        ),
    ]
