# Generated by Django 4.2.16 on 2026-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_donorresponse_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('donor_needed', 'Donor Needed'), ('assigned', 'Assigned'), ('donor_accepted', 'Donor Accepted'), ('scheduled', 'Scheduled'), ('schedule_accepted', 'Schedule Accepted'), ('allocated', 'Allocated'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('testing', 'Testing'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('schedule_accepted', 'Schedule Accepted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('donated', 'Donated'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
