# Generated by Django 4.2.16 on 2026-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0010_alter_bloodrequest_status_alter_donorresponse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorresponse',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
