# Generated by Django 4.2.16 on 2026-03-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0011_donorresponse_blood_pressure_donorresponse_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorresponse',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='donorresponse',
            name='temperature',
        ),
    ]
